[package]
name = "coap-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["codec", "net"] }
bytes = "1.1.0"
futures = "0.3.21"
async-trait = "0.1.53"
async-stream = "0.3.3"
pin-project = "1.0.10"
anyhow = "1.0.56"
thiserror = "1.0.30"
env_logger = "0.9.0"
log = "0.4.16"
coap-lite = "0.9.0"
sync_wrapper = "0.1.1"