[package]
name = "rust-coap-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = "0.7.0"
futures = "0.3.21"
async-trait = "0.1.53"
anyhow = "1.0.56"
thiserror = "1.0.30"
env_logger = "0.9.0"
log = "0.4.16"
coap-lite = "0.9.0"