name: coverage

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      env:
        COVERALLS_KEY: ${{ secrets.COVERALLS_KEY }}
      with:
        args: '--avoid-cfg-tarpaulin --coveralls "$COVERALLS_KEY"'
